export const BODY_TEXT = `A black hole is a region of spacetime where gravity is so strong that nothing, not even light or other electromagnetic waves, has enough energy to escape it. The theory of general relativity predicts that a sufficiently compact mass can deform spacetime to form a black hole. The boundary of no escape is called the event horizon. A black hole has a great effect on the fate and circumstances of an object crossing it, but it has no locally detectable features according to general relativity.

In many ways, a black hole acts like an ideal black body, as it reflects no light. Quantum field theory in curved spacetime predicts that event horizons emit Hawking radiation, with the same spectrum as a black body of a temperature inversely proportional to its mass. This temperature is of the order of billionths of a kelvin for stellar black holes, making it essentially impossible to observe directly.

Objects whose gravitational fields are too strong for light to escape were first considered in the eighteenth century by John Michell and Pierre-Simon Laplace. In 1916, Karl Schwarzschild found the first modern solution of general relativity that would characterize a black hole. David Finkelstein, in 1958, first published the interpretation of this solution as a region of space from which nothing can escape.

The idea of a body so massive that even light could not escape was briefly proposed by the English astronomical pioneer and clergyman John Michell in a letter published in November 1784. He correctly noted that such supermassive but nonradiating bodies might be detectable through their gravitational effects on nearby visible bodies. Scholars of the time were initially excited by the proposal but interest waned when the theory of light changed from a corpuscular theory to a wave theory, in which it was unclear what influence gravity would have.

If a black hole is very small, the radiation effects are expected to become very strong. A black hole with the mass of a car would have a diameter of about ten to the minus twenty-four meters and take a nanosecond to evaporate, during which time it would briefly have a luminosity of more than two hundred times that of the visible universe. A black hole with the mass of the planet Mercury would last for over ten billion years, longer than the current age of the universe.

The observation of gravitational waves from merging black holes has provided direct evidence that black holes exist. The first such observation was made in September 2015 by the LIGO gravitational wave observatory. In April 2019, the Event Horizon Telescope released the first direct image of a black hole, which revealed the supermassive black hole at the center of Messier 87. As of 2023, the nearest known black hole to Earth is Gaia BH1, which is about sixteen hundred light-years away.

Spacetime around a black hole is not simply curved, it is twisted, dragged, and stretched by the immense gravitational field. Objects falling toward the event horizon experience spaghettification, the vertical stretching and horizontal compression by growing tidal forces. For a nonrotating black hole, this effect becomes significant at a distance that depends on the mass. For supermassive black holes, an observer could cross the event horizon without noticing any immediate change, only realizing later that escape has become impossible. The singularity at the center, where density becomes infinite and spacetime curvature diverges, remains one of the great unsolved mysteries of physics.`

export const BODY_FONT = '18px "EB Garamond", Georgia, serif'
export const BODY_LINE_HEIGHT = 28
export const MIN_SLOT_WIDTH = 40
